### PR TITLE
build(docs): Update the readme file

### PR DESCRIPTION
**Pull request by hamada147**
Update the readme file.

### CODE REVIEW

**Review by FabioPinheiro — CHANGES_REQUESTED** [review]
The docs LGTM.
But what organisation/groupId name is this `io.iohk.atala.prism.anoncredskmp`?
Why not `io.iohk.atala`?

**Comment by hamada147** [comment]
> What organisation name is this `io.iohk.atala.prism.anoncredskmp`? Why not `io.iohk.atala`?

Hey @FabioPinheiro,
All our KMP projects have the same beginning for the group ID `io.iohk.atala.prism` then the project name. For this project it is `anoncredskmp`.
We have Apollo as `io.iohk.atala.prism.apollo` and we have the DIDPeer as `io.iohk.atala.prism.didcomm` and for wallet SDK we have `io.iohk.atala.prism.walletsdk`
That's why we have this package as `io.iohk.atala.prism.anoncredskmp`

**Comment by FabioPinheiro** [comment]
> > What organisation name is this `io.iohk.atala.prism.anoncredskmp`? Why not `io.iohk.atala`?
> 
> Hey @FabioPinheiro, All our KMP projects have the same beginning for the group ID `io.iohk.atala.prism` then the project name. For this project it is `anoncredskmp`. We have Apollo as `io.iohk.atala.prism.apollo` and we have the DIDPeer as `io.iohk.atala.prism.didcomm` and for wallet SDK we have `io.iohk.atala.prism.walletsdk` That's why we have this package as `io.iohk.atala.prism.anoncredskmp`

What a mass!

**Review by FabioPinheiro — APPROVED** [review]
Don't even know what to say

**Pull request merged**
